ahaberberger_layout:
    resource: "@ahaberbergerLayoutBundle/Resources/config/routing.yml"
    prefix:   /

ahaberberger_contentful:
    resource: "@ahaberbergerContentfulBundle/Resources/config/routing.yml"
    prefix:   /contentful/

